name: CI

on: 
  push:
    branches: 
    - "*"
  pull_request:
    branches: 
    - master

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: SPM build
      run: swift build

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['5.0', '5.1']
    services:
      localstack:
        image: localstack/localstack
        # ports:
        # - 4567-4597:4567-4597
        env:
          SERVICES: 'apigateway,dynamodb,iam,s3,sns,sqs,ssm'
        options: >-
          --health-cmd "awslocal s3 ls"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: swift:${{ matrix.tag }}
      volumes:
      - $GITHUB_WORKSPACE:/src
      options: --workdir /src
    env:
      APIGATEWAY_ENDPOINT : "http://localstack:4567"
      DYNAMODB_ENDPOINT   : "http://localstack:4569"
      SNS_ENDPOINT        : "http://localstack:4575"
      SQS_ENDPOINT        : "http://localstack:4576"
      SSM_ENDPOINT        : "http://localstack:4583"
      IAM_ENDPOINT        : "http://localstack:4593"
    steps:
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata libssl-dev zlib1g-dev
    - name: Print ports
      run: |
        echo "localstack:4567 ${{ job.services.localstack.ports['4567'] }}"
        echo "localstack:4569 ${{ job.services.localstack.ports['4569'] }}"
        echo "localstack:4575 ${{ job.services.localstack.ports['4575'] }}"
        echo "localstack:4576 ${{ job.services.localstack.ports['4576'] }}"
        echo "localstack:4583 ${{ job.services.localstack.ports['4583'] }}"
        echo "localstack:4593 ${{ job.services.localstack.ports['4593'] }}"
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Test
      run: swift test -Xswiftc -DDEBUG
